#!/bin/bash

myArray=("/scratch/varunt/finBERT/models/downstream_eval_gridsearch/pretraining_grid_public/hfrun_decay0.0005_lr5e-5_ss512_bs256_results_finbert_dir" "/scratch/varunt/finBERT/models/downstream_eval_gridsearch/" "pretraining_grid_public/hfrun_decay0.0005_lr5e-6_ss512_bs256_results_finbert_dir" "/scratch/varunt/finBERT/models/downstream_eval_gridsearch/pretraining_grid_public/hfrun_decay0.0005_lr5e-7_ss512_bs256_results_finbert_dir" "/scratch/varunt/finBERT/models/downstream_eval_gridsearch/pretraining_grid_public/hfrun_decay0.001_lr1e-5_ss512_bs256_results_finbert_dir" "/scratch/varunt/finBERT/models/downstream_eval_gridsearch/pretraining_grid_public/hfrun_decay0.001_lr1e-6_ss512_bs256_results_finbert_dir" "/scratch/varunt/finBERT/models/downstream_eval_gridsearch/pretraining_grid_public/hfrun_decay0.001_lr5e-5_ss512_bs256_results_finbert_dir" "/scratch/varunt/finBERT/models/downstream_eval_gridsearch/pretraining_grid_public/hfrun_decay0.001_lr5e-6_ss512_bs256_results_finbert_dir" "/scratch/varunt/finBERT/models/downstream_eval_gridsearch/pretraining_grid_public/hfrun_decay0.001_lr5e-7_ss512_bs256_results_finbert_dir" "/scratch/varunt/finBERT/models/downstream_eval_gridsearch/pretraining_grid_public/hfrun_decay0.005_lr1e-5_ss512_bs256_results_finbert_dir" "/scratch/varunt/finBERT/models/downstream_eval_gridsearch/pretraining_grid_public/hfrun_decay0.005_lr1e-6_ss512_bs256_results_finbert_dir" "/scratch/varunt/finBERT/models/downstream_eval_gridsearch/pretraining_grid_public/hfrun_decay0.005_lr5e-5_ss512_bs256_results_finbert_dir" "/scratch/varunt/finBERT/models/downstream_eval_gridsearch/pretraining_grid_public/hfrun_decay0.005_lr5e-6_ss512_bs256_results_finbert_dir" "/scratch/varunt/finBERT/models/downstream_eval_gridsearch/pretraining_grid_public/hfrun_decay0.005_lr5e-7_ss512_bs256_results_finbert_dir" "/scratch/varunt/finBERT/models/downstream_eval_gridsearch/pretraining_grid_public/hfrun_decay0.01_lr1e-5_ss512_bs256_results_finbert_dir" "/scratch/varunt/finBERT/models/downstream_eval_gridsearch/pretraining_grid_public/hfrun_decay0.01_lr1e-6_ss512_bs256_results_finbert_dir" "/scratch/varunt/finBERT/models/downstream_eval_gridsearch/pretraining_grid_public/hfrun_decay0.01_lr5e-5_ss512_bs256_results_finbert_dir" "/scratch/varunt/finBERT/models/downstream_eval_gridsearch/pretraining_grid_public/hfrun_decay0.01_lr5e-6_ss512_bs256_results_finbert_dir" "/scratch/varunt/finBERT/models/downstream_eval_gridsearch/pretraining_grid_public/hfrun_decay0.01_lr5e-7_ss512_bs256_results_finbert_dir")

#for folder in /scratch/varunt/finBERT/models/downstream_eval_gridsearch/pretraining_grid_public/*; do
for folder in ${myArray[@]}; do
    echo "${folder}"
    run_folder=$(echo "${folder}/" | cut -d'/' -f8)
    echo "${run_folder}"
    log_file="downstream_eval_gridsearch_results/public/downstreamgrid_${run_folder}.txt"
    echo "${log_file}"
    CUDA_VISIBLE_DEVICES=0 python3 -u run_seeds.py --model_name_or_path ${folder} 2>&1 --start_seed 0 --end_seed 4 --type public | tee ${log_file}
    rm -rf /scratch/varunt/finbert_clpath/public
done